### ISSUE TITLE
Crash with Blood Magic's book

### ISSUE THREAD

**Issue by EXTER7** [TeamAmeriFrance/Guide-API#10]
Using Guide-API 1.0.1-19 and BloodMagic 1.3.3-2
When opening the "The Divination Sigil" entry in Blood Magic's "Sanguine Scientiem" book, the game crashes.

Crash report: http://pastebin.com/i95srmGx

**Comment by zISKo666** [comment]
I opened another entry but got the same crash.
Guide-API 1.0.1-19
BloodMagic 1.3.3-2

**Comment by TehNut** [comment]
Use Build 16 for Blood Magic. Way was doing his custom recipe pages "wrong" so when we cleaned them up, it broke backwards compatibility with it. I've already notified him.

This needs to be fixed on BM's end.

**Comment by manuelstamm** [comment]
"Build 16 for Blood Magic." Is there a link for that or is it only self build?

**Comment by TehNut** [comment]
Use the latest version of each mod.

**Comment by manuelstamm** [comment]
Thanks
