### ISSUE TITLE
Spawn eggs with nbt data not working 

### ISSUE THREAD

**Issue by Trhod17** [TeamAmeriFrance/Guide-API#100]
second times the charm.
i am making a mod and i am trying to make a guide book but the spawn eggs dont work they are just white

new ItemStack(Items.SPAWN_EGG,16,120

that is what i have for my spawn eggs

**Comment by TehNut** [comment]
That constructor specifies size and meta. Not NBT. You are *not* creating that stack properly.

**Comment by Trhod17** [comment]
16 is the size of the stack and 120 is the meta

**Comment by TehNut** [comment]
***Neither of which are NBT***
