### ISSUE TITLE
[MC 1.12.2] Guide API 1.12-2.1.4-57 works, but isn't marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [TeamAmeriFrance/Guide-API#102]
[Guide API 1.12-2.1.4-57](https://minecraft.curseforge.com/projects/guide-api/files/2466858) appears to work on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but isn't marked as such on Curse disallowing modpacks from using it.

**Comment by TehNut** [comment]
Thanks, fixed.

**Comment by sandalle** [comment]
Thanks for the quick turnaround, @TehNut ! :)
