### ISSUE TITLE
PageHelper.pagesForLongText split pages before localization

### ISSUE THREAD

**Issue by Lykrast** [TeamAmeriFrance/Guide-API#105]
Using this method, I was expecting being able to write long lines of text in my lang file and let this method handle the page wraps, but instead I get this result:
![image](https://user-images.githubusercontent.com/8684850/39298084-8d6d1efa-4945-11e8-9881-4c480b2574fe.png)
The code for this particular entry is :
```java
List<IPage> explosionFurnace = new ArrayList<>();
explosionFurnace.addAll(PageHelper.pagesForLongText(prefix("explosionfurnace.content")));
entries.put(new ResourceLocation(prefix("explosionfurnace")), new Entry(explosionFurnace, prefix("explosionfurnace")));
```

**Comment by TehNut** [comment]
Well... yeah? You're supposed to pass your localized string. Hence why the param is called `locText`.
