### ISSUE TITLE
Real guide for your API

### ISSUE THREAD

**Issue by VladoCC** [TeamAmeriFrance/Guide-API#106]
Hello I know that it will cot much time, but can you create real guide for developers? What I found on ReadTheDocs not informative.
I and many other developers want to know all methods that we have.

For example: I want to create book with images and I do not know? can I use your API or I need to create my own.

**Comment by TehNut** [comment]
The docs expect that you have some knowledge of looking into things yourself. It shows you how to get started, the rest is up to you.
