### ISSUE TITLE
NoSuchMethodError when starting minecraft with the new blood magic book.

### ISSUE THREAD

**Issue by levicc00123** [TeamAmeriFrance/Guide-API#11]
full crash log can be found [here](https://gist.github.com/levicc00123/15a2931b03868dbd2f24)

**Comment by levicc00123** [comment]
Never mind, I'm an idiot. :(

**Comment by TehNut** [comment]
For anybody who looks at this in the future, it is caused (at this point in time) by Sanguimancy (and old Blood Magic versions) extending `PageIRecipe` instead of implementing `IRecipeRenderer`. See these issues for more information: #10, WayofTime/BloodMagic#339, Tombenpotter/Sanguimancy#64
