### ISSUE TITLE
Page Text Don't Support Hot Reload

### ISSUE THREAD

**Issue by TartaricAcid** [TeamAmeriFrance/Guide-API#110]
I am a mod translator, when I change the language from English to Chinese, I was surprised to found that all entries in the book have not changed, reload the resource pack also is useless.
By reading the source code, it seems that the book's entry is load when registered the item.
I hope to add a hot reload function (maybe a command is better).

**Comment by TehNut** [comment]
~~Strange. Nothing should be cached. It's all translated on the fly.~~

Nevermind I'm actually just stupid.
