### ISSUE TITLE
[SOLVED] Smelting Recipe Display Not Correct

### ISSUE THREAD

**Issue by Iceflame3029** [TeamAmeriFrance/Guide-API#119]
I added a page to display my custom smelting recipe. But it doesn't display correctly.
Could anyone tell me where goes wrong?
(The recipe can work in minecraft world properly. And my minecraft version is 1.12.2)

p.s. Sorry for the texture of the ore. I haven't done it yet.
![2018-10-02_01 17 00](https://user-images.githubusercontent.com/31977308/46304564-956c0d00-c5e1-11e8-8d20-f3adab5eaff8.png)

These are my code.
<img width="957" alt="screen" src="https://user-images.githubusercontent.com/31977308/46304591-b2a0db80-c5e1-11e8-9d28-d275fce06e5f.png">
<img width="956" alt="default" src="https://user-images.githubusercontent.com/31977308/46304602-ba608000-c5e1-11e8-957b-45bd6d5ac8a9.png">
<img width="957" alt="m" src="https://user-images.githubusercontent.com/31977308/46304615-c1878e00-c5e1-11e8-8d8d-65ca3aeee3ae.png">

**Comment by TehNut** [comment]
You are registering your smelting recipe during init and not the recipe registry event

**Comment by Iceflame3029** [comment]
So what exactly should I do?

**Comment by Iceflame3029** [comment]
Oh! I found what goes wrong and I solved that.
Thanks for your help.
