### ISSUE TITLE
Maven is offline

### ISSUE THREAD

**Issue by Lothrazar** [TeamAmeriFrance/Guide-API#131]
http://tehnut.info/maven/

Is there a backup? I want to avoid removing support for this api

**Comment by TehNut** [comment]
I'm working on bringing it back up, but for now you can use Curse's maven to pull the files.

**Comment by X-Niter** [comment]
Any new news on this? 
I gave the Curse forge maven a go and that was about 3 hours down the drain of not working. 
Not to mention there info they have on it did not match up when taking a glance at it.

**Comment by TehNut** [comment]
`https://maven.tehnut.info`, same group, same artifact id, latest version listed on curse

**Comment by X-Niter** [comment]
> `https://maven.tehnut.info`, same group, same artifact id, latest version listed on curse

Access Denied.

**Comment by TehNut** [comment]
Are you trying to browse it? You can't do that.

It's definitely there, though. 

https://maven.tehnut.info/info/amerifrance/guideapi/Guide-API/1.12-2.1.8-63/Guide-API-1.12-2.1.8-63.jar

**Comment by X-Niter** [comment]
```
maven { // GuideAPI
        url = "https://maven.tehnut.info/"
    }

deobfCompile "info.amerifrance.guideapi:Guide-API:1.12-2.1.8-63"
```

`https://maven.tehnut.info/info/amerifrance/guideapi/Guide-API/1.12-2.1.8-63/Guide-API-1.12-2.1.8-63.pom'. Received status code 403 from server: Forbidden`


I thought for a second I had a typo but it's all checking out.
