### ISSUE TITLE
Guidebook crash me in loading screen, Initializing Phase

### ISSUE THREAD

**Issue by Crowgue** [TeamAmeriFrance/Guide-API#132]
1.12.2
[https://pastebin.com/PPYLqz2b](url)
[https://pastebin.com/yAgm2wvw](url)
In the "Initializing Mod" phase Guidebook crash me and I tried to remove some mod but I can not find the incompatibility.
I have read the resolved issues but I have not found a solution for me, in most cases of people with my same problem it was enough to remove the vampirism mod, but I do not have it in the modpack.

Help Please

**Comment by TehNut** [comment]
That is not this mod
