### ISSUE TITLE
Need help with JSON book

### ISSUE THREAD

**Issue by maxanier** [TeamAmeriFrance/Guide-API#14]
Hello,
I would like to add a guide book to my mod Vampirism https://github.com/TeamLapen/Vampirism, since your Guide-API looks quite cool I would like to use it, preferably the JSON version since I hope it is easier to maintain. I already added Guide-API as dependency and create the Optional methods for registration. But I'm not sure how to create a book from a JSON file, I found amerifrance.guideapi.util.serialization.BookCreator.createBookFromJson, but it takes a File as param and I only got an InputStream since my json file will be in the jar file. So I don't think it is meant to be used by other mods, does it? 
I hope you can extend the docs with a short explanation how to use json books
Thanks :)

**Comment by TehNut** [comment]
You don't use the JSON books if you're a mod developer. Those are for pack makers who want to provide information about their pack. They're only meant to be loaded from the config folder.

And trust me when I say, the JSON books are a bitch to work with.

**Comment by maxanier** [comment]
Ok thanks, I will try to implement the book in Java then.
A short note or explanation about json books might be helpful for other mod developers.

**Comment by TehNut** [comment]
Documentation is hard to write. It takes time

**Comment by maxanier** [comment]
Yeah I struggle with keeping my wiki up-to-date as well, It just does not make as much fun as modding itself. Just was not sure if you just missed mentioning this. Thanks again for creating and maintaining such an API, it saves a lot of time. (Just in case you are interested: I'm planning to add this as an optional dependency, which the users have to install to get an ingame guide; similar to Blood Magic)
