### ISSUE TITLE
I'm here to complain and suggest

### ISSUE THREAD

**Issue by Arcaratus** [TeamAmeriFrance/Guide-API#15]
Complaints: Shapeless recipe shows up as Shaped Recipe
                   You should do something similar to the non-existent Furnace recipes for crafting recipes (it                    will crash if it cannot find the items)

Other than that, all is good and well, pretty neat considering all the mod author has to do is type long pages
Suggestions:  (I know you're not going to do this but) Make a bigger book (or make the dimensions scalable?) <--images of higher resolution look weird otherwise
                      Put multiple crafting recipes onto one page? (like NEI) (and furnace recipes too :P)
                      Word wrapping is sometimes off a bit, maybe make the text justified?
                      Title options for the title page (images, text where you want and what size you want)

This is a lot to ask; I don't actually expect much of these to be something that'll be implemented in the near future, but as always, great job!

**Comment by TehNut** [comment]
> Shapeless recipe shows up as Shaped Recipe

Explain?

> Make a bigger book

No, extend stuff and do it yourself.

> Put multiple crafting recipes onto one page?

Create your own page for that?

> Word wrapping is sometimes off a bit, maybe make the text justified?

No, justified is ugly as shit.

> Title options for the title page

Again, create your own pages...

**Comment by Tombenpotter** [comment]
He cannot extend stuff and create a bigger book. Unless he redoes the whole GUIs....

About the other ideas/complaints, the point of the mod was to provide basic things for authors to use. If they didn't like it, all they had to do was to create a new page. The mod was made to be ultra compatible like that.

**Comment by Arcaratus** [comment]
I mean, I knew how to create a page...:P But when I register a Shapeless Recipe to display, the title labels as Shaped Recipe.

**Comment by Tombenpotter** [comment]
Extend PageBase

**Comment by Arcaratus** [comment]
My first copy paste attempt at a new page :P

![](http://i.imgur.com/hLZPvrn.png)

**Comment by Tombenpotter** [comment]
See? That was the original plan. Don't like it, do it yourself the way you want :D

**Comment by Arcaratus** [comment]
Even better progress report, although can't figure out why it's like this (the black bars)
https://twitter.com/Arcaratus/status/618864152015204352/photo/1

**Comment by tterrag1098** [comment]
This misnaming is my fault, I can fix it shortly.

**Comment by Arcaratus** [comment]
Ah, thanks
