### ISSUE TITLE
Is the 1.8 Branch working or close to working?

### ISSUE THREAD

**Issue by EliSussman** [TeamAmeriFrance/Guide-API#17]
Is the 1.8 Branch working or close to working? If so, how would I add this unreleased version to my project. If not, ETA?

Thanks,
-KCE

**Comment by Tombenpotter** [comment]
If l remember correctly, the 1.8 branch was working fine. It just wasn't released... @TehNut can you do something about this?

**Comment by EliSussman** [comment]
Thanks for responding. When you upload the 1.8 version, please post a link here :)

**Comment by EliSussman** [comment]
Any updates? @Tombenpotter @TehNut I don't mean to rush, but I kind of need to start working on this.

**Comment by Tombenpotter** [comment]
If you don't plan on releasing in a week or so, just use what is on the 1.8 branch. I'm in holidays, so I can't do much :/

**Comment by EliSussman** [comment]
Do I have to turn it into a jar? Or do I download all the files? If the latter, where do I put all the files?

Also, enjoy your holiday :-)

**Comment by Tombenpotter** [comment]
You can do either. If you don't want to jar it, just drop the thing in src/main. 

Thanks :)

**Comment by EliSussman** [comment]
I added it into my environment and it works, may I change some code and then distribute it with my mod? Or do I have to have people download both of them separately?

**Comment by TehNut** [comment]
I'm currently out of town, though I can look at getting an official build out at some point. IIRC, there were a few minor things that weren't working.

**Comment by EliSussman** [comment]
So its been a little over 2 weeks and I don't mean to rush, but any update? :-)

**Comment by Tombenpotter** [comment]
It's been two weeks, and I'm still in vacation ! Coming back around the 20ish

**Comment by TehNut** [comment]
I've also been busy with work. Be patient.

**Comment by TehNut** [comment]
I am currently bringing forward all new features/fixes to the 1.8 branch. Expect an official release in the next few hours. Tomorrow evening at the latest.

**Comment by TehNut** [comment]
Build is now live.

[Jenkins](http://tehnut.info/jenkins/job/Guide-API-1.8/)
[Curseforge](http://minecraft.curseforge.com/mc-mods/228832-guide-api/files/2253496)

**Comment by Tombenpotter** [comment]
And I'm back tomorrow!

**Comment by TehNut** [comment]
\o/
