### ISSUE TITLE
“/n” doesnt work when using zh_CN.lang file(simpified Chinese)

### ISSUE THREAD

**Issue by Joccob** [TeamAmeriFrance/Guide-API#18]
As you can see from the picture, I try to use /n to start a new paragraph, but it doesnt work. And also I dont know what to do to creat a new page (or is that automatic?)
![image 2](https://cloud.githubusercontent.com/assets/11893599/9088012/878c4078-3bc0-11e5-9617-838788c233f7.png)

**Comment by tterrag1098** [comment]
It's \n, backslash. Not /n.

**Comment by TehNut** [comment]
> And also I dont know what to do to creat a new page (or is that automatic?)

Use [PageHelper.pagesForLongText(String, int)](https://github.com/TeamAmeriFrance/Guide-API/blob/1.7.10/src/main/java/amerifrance/guideapi/api/util/PageHelper.java#L18).

**Comment by Joccob** [comment]
I tried \n as well, doesn't work
