### ISSUE TITLE
Custom icon for book

### ISSUE THREAD

**Issue by Xilef11** [TeamAmeriFrance/Guide-API#20]
Not sure if this is already possible, but I can't find a way to set a custom icon for a guide book other than extending/modifying ItemGuideBook, GuideRegistry (to put "my" version of ItemGuideBook in the itemStack) and some of the GUI system (so it recognises "my" GuideRegistry/ItemGuideBook)

**Comment by TehNut** [comment]
For 1.7.10:

https://github.com/TeamAmeriFrance/Guide-API/blob/1.7.10/src/main/java/amerifrance/guideapi/api/util/BookBuilder.java#L73-L76

Provide it as you would a ResourceLocation.

For 1.8:

https://github.com/TeamAmeriFrance/Guide-API/blob/1.8/src/main/java/amerifrance/guideapi/api/util/BookBuilder.java#L73-L76

Stops us from registering an inventory render for your specific item so you can set your own.

**Comment by Xilef11** [comment]
oh, I just realised I added the wrong version to my build.gradle (so BookBuilder didn't exist)...
