### ISSUE TITLE
GUI font size is broken.

### ISSUE THREAD

**Issue by DarkEternity909** [TeamAmeriFrance/Guide-API#21]
Using any of the "Blood Magic"-related books, the font is oversized and placed half-way off the page render itself.

Here's a screenshot of the Blood Magic book "Sanguine Scientiem":
https://www.dropbox.com/s/vq4feq6nsarlib0/2016-01-26_17.56.39.png?dl=0

There's no listed options in any of the configs, for either this mod or the mods that use it, for changing the GUI size of the books. Resizing the Game GUI still keeps the font in that postion and size in comparison to the book.

**Comment by TehNut** [comment]
Downgrade to build 20.
