### ISSUE TITLE
You didn't post a deobf version for download anywhere

### ISSUE THREAD

**Issue by Da-Technomancer** [TeamAmeriFrance/Guide-API#22]
(sorry I put this here, where it doesn't really belong, but it was the only way I could find of contacting you) It seems like you forgot to release the deobf version for download on maven. Just letting you know.

**Comment by TehNut** [comment]
You don't use Deobf versions in 1.8.9. Use `deobfCompile` instead of `compile`. I haven't updated the docs, yet.

**Comment by Da-Technomancer** [comment]
Got it, thanks!
