### ISSUE TITLE
updating 1.7.10 version

### ISSUE THREAD

**Issue by johnfg2610** [TeamAmeriFrance/Guide-API#24]
Would we be able to get a release of the latest github version as we are having issues with a item that no longer exists and is fixed in this version. This would be greatly appreciated

**Comment by TehNut** [comment]
The latest build has the latest source on the `1.7.10` branch already.

**Comment by johnfg2610** [comment]
apparently a line is diffrent that is causing huge issues 
if (!GuideRegistry.isEmpty() && GuideRegistry.getSize() > stack.getItemDamage() && GuideRegistry.getBook(stack.getItemDamage()).itemTexture == null) {
            if (pass == 0)
                return GuideRegistry.getBook(stack.getItemDamage()).bookColor.getRGB();
            else
                return super.getColorFromItemStack(stack, pass);
        } else {
            return super.getColorFromItemStack(stack, pass);
        }
this i think

**Comment by TehNut** [comment]
The last commit made was https://github.com/TeamAmeriFrance/Guide-API/commit/c12803efff75a9f61e8306e2cced8542b9f09273. The last commit built was that, as well. http://tehnut.info/jenkins/job/Guide-API/job/1.7.10/changes

**Comment by johnfg2610** [comment]
i can grab u the crash log we are having
[crash-2016-03-13_11.42.29-client.txt](https://github.com/TeamAmeriFrance/Guide-API/files/174782/crash-2016-03-13_11.42.29-client.txt)
[crash-2016-03-11_21.47.45-client.txt](https://github.com/TeamAmeriFrance/Guide-API/files/174783/crash-2016-03-11_21.47.45-client.txt)

**Comment by TehNut** [comment]
You are looking at a completely different method. `func_77624_a` is `addInformation`, not `getColorFromItemStack`. Caused by this [line](https://github.com/TeamAmeriFrance/Guide-API/blob/1.7.10/src/main/java/amerifrance/guideapi/items/ItemGuideBook.java#L162). 

Please take note of the description of that commit.

**Comment by johnfg12** [comment]
not going to lie im not a java person whats the issue how do i fix it lol

**Comment by johnfg2610** [comment]
just as point thanks for the help im not a dev im making a mod pack and this has caused many issues thanks :)
