### ISSUE TITLE
Book text is blacked out

### ISSUE THREAD

**Issue by xilni** [TeamAmeriFrance/Guide-API#28]
The text in the Sanguimancy and Blood Magic book is all blacked out and the crafting recipes in the book appear a bit mangled as well.

I've included sample images that illustrate the problem. The only legible pages are the index pages in each category, I've included one in the below images.

I originally [posted this to Sanguimancy as an issue](https://github.com/Tombenpotter/Sanguimancy/issues/107) but further research has led me to believe this may be a Guide API issue.

**Versions used (This is just FTB Infinity 2.5.0 with Sanguimancy added):**
Minecraft 1.7.10
Forge 10.13.4.1614
Guide-API-1.7.10-1.0.1-20
BloodMagic-1.7.10-1.3.3-17
Sanguimancy-1.7.10-1.1.9-35

Images of the problem:
![javaw_2016-05-15_17-42-02](https://cloud.githubusercontent.com/assets/5873991/15276947/85968da8-1ac4-11e6-8dde-9810582db85e.png)
![javaw_2016-05-15_17-42-08](https://cloud.githubusercontent.com/assets/5873991/15276948/85972218-1ac4-11e6-9010-7924e4ed96ea.png)
![javaw_2016-05-15_16-47-07](https://cloud.githubusercontent.com/assets/5873991/15276930/cf3c506a-1ac3-11e6-9f4e-532eb8efaf9f.png)
![javaw_2016-05-15_16-47-19](https://cloud.githubusercontent.com/assets/5873991/15276929/cf3c2950-1ac3-11e6-9ab9-f54f9a9c8d05.png)
![javaw_2016-05-15_16-47-21](https://cloud.githubusercontent.com/assets/5873991/15276931/cf3cf934-1ac3-11e6-9bc5-a3aa4f2e819b.png)

**Comment by TehNut** [comment]
https://www.reddit.com/r/feedthebeast/comments/4rhle3/anyone_know_what_is_up_with_this_guide_api_book/
