### ISSUE TITLE
An unknown persistent registry type "guideapi:books" has been encountered.

### ISSUE THREAD

**Issue by unknownname** [TeamAmeriFrance/Guide-API#30]
MC version 1.9.4
Forge version 12.17.0.1937

I am currently getting the error message when i upgrade the Old Minecraft world to Lastest MC version. I am not sure that this issue is caused by Guide API mod or Forge itself not deleting the registry properly from the existing world. Attached is FML logs:

How to reproduce:
Create a world with Guide Api mod installed
Then delete the Guide Api and try to restart the server.

[fml-server-latest.txt](https://github.com/TeamAmeriFrance/Guide-API/files/294466/fml-server-latest.txt)

**Comment by TehNut** [comment]
This is a Forge issue.
