### ISSUE TITLE
Guide api causeing repeated crashes

### ISSUE THREAD

**Issue by ripchourd** [TeamAmeriFrance/Guide-API#36]
I have a bunch of mods installed that already work including blood magic but trying to load addons that require Guide-API-1.7.10-1.0.1-20 causes it to crash.

Here is the crash log:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/18/16 10:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.copy()Lnet/minecraft/item/ItemStack;
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.copy()Lnet/minecraft/item/ItemStack;
    at amerifrance.guideapi.api.GuideRegistry.getItemStackForBook(GuideRegistry.java:62)
    at com.teamdman_9201.nova.NOVA.initRecipes(NOVA.java:145)
    at com.teamdman_9201.nova.NOVA.load(NOVA.java:226)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 354479216 bytes (338 MB) / 804233216 bytes (766 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 143 mods loaded, 132 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    modJ_StarMinerCore{0.9.7} [StarMinerCore](minecraft.jar) 
    UCHI    appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    LambdaLib|Core{1.2.1} [LambdaLib|Core](minecraft.jar) 
    UCHI    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHI    PlayerAPI{1.4} [Player API](minecraft.jar) 
    UCHI    VeinMiner_coremod{null_build-null} [Core mod](minecraft.jar) 
    UCHI    OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHI    ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    UCHI    FLabsBF{4.3} [Better Furnaces]([1.7.10]Better_Furnaces_V4.3.jar) 
    UCHI    LambdaLib{1.2.1} [LambdaLib](LambdaLib-1.2.1.jar) 
    UCHI    CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHI    academy-craft{1.0.2} [Academy Craft](AcademyCraft-1.0.2.jar) 
    UCHI    appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
    UCHI    bdlib{1.9.2.104} [BD Lib](bdlib-1.9.2.104-mc1.7.10.jar) 
    UCHI    ae2stuff{0.5.0.56} [AE2 Stuff](ae2stuff-0.5.0.56-mc1.7.10.jar) 
    UCHI    modJ_StarMiner{0.9.7} [Starminer Mod](Anti-Gravity-Mod-1.7.10.jar) 
    UCHI    AppleCore{1.3.2} [AppleCore](AppleCore-mc1.7.10-1.3.2.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    BBG{1.0.0} [BetterBedrockGen](BBG-1.0.0.jar) 
    UCHI    BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHI    AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHI    guideapi{1.7.10-1.0.1-20} [Guide-API](Guide-API-1.7.10-1.0.1-20.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHI    MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHI    BloodArsenal{1.2-5} [Blood Arsenal](BloodArsenal-1.7.10-1.2-5.jar) 
    UCHI    WaslieCore{1.1} [WaslieCore](WaslieCore-1.7.10.jar) 
    UCHI    BloodUtils{1.4} [BloodUtils](BloodUtils-1.4_B0.jar) 
    UCHI    BrandonsCore{1.0.0.12} [Brandon's Core](BrandonsCore-1.0.0.12.jar) 
    UCHI    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHI    menagerie{1.0} [menagerie](dark_menagerie-1.7.10-beta-3.1a.jar) 
    UCHI    darkcore{0.3} [Dark Core](darkcore-0.3-86.jar) 
    UCHI    OmnisCore{0.1.0} [Omnis Core](OmnisCore-1.7.10 - 0.0.6-universal.jar) 
    UCHI    dimensionalPockets{0.11.4.1} [Dimensional Pockets](DimensionalPockets-1.7.10-0.11.4.1-universal.jar) 
    UCHI    DraconicEvolution{1.0.2h} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2h.jar) 
    UCHI    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHI    endercore{1.7.10-0.2.0.36_beta} [EnderCore](EnderCore-1.7.10-0.2.0.36_beta.jar) 
    UCHI    EnderIO{1.7.10-2.3.0.427_beta} [Ender IO](EnderIO-1.7.10-2.3.0.427_beta.jar) 
    UCHI    EnderOre{1.0.4} [EnderOre](EnderOre-1.7.10-1-0-4.jar) 
    UCHI    enderRift{@VERSION} [Ender-Rift](EnderRift-0.53.jar) 
    UCHI    EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHI    EnderTech{1.7.10-0.3.2.405} [EnderTech](EnderTech-1.7.10-0.3.2.405.jar) 
    UCHI    evilcraft{0.9.8} [EvilCraft](EvilCraft-1.7.10-0.9.8.jar) 
    UCHI    extracells{2.3.14} [Extra Cells 2](ExtraCells-1.7.10-2.3.14b197.jar) 
    UCHI    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHI    ExtraTiC{1.4.6} [ExtraTiC](ExtraTiC-1.7.10-1.4.6.jar) 
    UCHI    GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.462.jar) 
    UCHI    GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.462.jar) 
    UCHI    HoloInventory{1.9.1.124} [HoloInventory](HoloInventory-1.7.10-1.9.1.124.jar) 
    UCHI    iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHI    ImLookingAtBlood{1.1} [I'm Looking At Blood](ImLookingAtBlood-1.7.2-1.1a.jar) 
    UCHI    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](Inventory-Tweaks-Mod-1.7.10.jar) 
    UCHI    InventoryPets{1.4.8} [Inventory Pets](inventorypets-1.7.10-1.4.8-universal.jar) 
    UCHI    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHI    JABBA{1.2.2} [JABBA](Jabba-1.2.2_1.7.10.jar) 
    UCHI    journeymap{5.1.4p1} [JourneyMap](journeymap-1.7.10-5.1.4p1-unlimited.jar) 
    UCHI    Mekanism{9.0.3} [Mekanism](Mekanism-1.7.10-9.0.3.277.jar) 
    UCHI    magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core](magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
    UCHI    magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury](magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
    UCHI    MekanismGenerators{9.0.3} [MekanismGenerators](MekanismGenerators-1.7.10-9.0.3.277.jar) 
    UCHI    MekanismTools{9.0.3} [MekanismTools](MekanismTools-1.7.10-9.0.3.277.jar) 
    UCHI    QVBACalculator{1.1} [Calculator](MinecraftCalculator_v1.10.jar) 
    UCHI    mfrmagiccropscompat{1.1} [MinefactoryReloaded & MagicalCrops extra compatibility](minefactory-magicalcrops-compatibility-1.2.jar) 
    UCHI    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHI    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UCHI    numina{0.4.0.131} [Numina](Numina-0.4.0.131.jar) 
    UCHI    powersuits{0.11.0.301} [MachineMuse's Modular Powersuits](ModularPowersuits-0.11.0.301.jar) 
    UCHI    Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHI    NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHI    neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHI    neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](NotEnoughResources-1.7.10-0.1.0-122.jar) 
    UCHE    NOVA{2015-10-09} [NOVA](NOVA-2015-10-09-universal.jar) 
    UCHI    OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1 %281%29.jar) 
    UCHI    OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1 %281%29.jar) 
    UCHI    PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
    UCHI    SonarCore{1.1.3} [SonarCore](SonarCore-1.7.10-1.1.3.jar) 
    UCHI    PracticalLogistics{0.2.4} [Practical Logistics](Practical-Logistics-1.7.10-0.2.4.jar) 
    UCHI    ProjectE{1.7.10-PE1.10.0} [ProjectE](ProjectE-1.7.10-PE1.10.0.jar) 
    UCHI    quantumenergy{0.6} [Quantum Energy](quantumenergy-1.7.10-0.6.jar) 
    UCHI    quantumflux{1.7.10-1.3.4} [QuantumFlux](QuantumFlux-1.7.10-1.3.4.jar) 
    UCHI    RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHI    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHI    xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) 
    UCHI    rftools{4.23} [RFTools](rftools-4.23.jar) 
    UCHI    Roguelike{1.5.0} [Roguelike Dungeons](roguelike-1.7.10-1.5.0b.jar) 
    UCHI    runicdungeons{1.1.7b} [Runic Dungeons](RunicDungeons-1.1.7b.jar) 
    UCHI    Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy](Sanguimancy-1.7.10-1.1.9-35.jar) 
    UCHI    SanguineExtras{1.3.2} [Sanguine Utilities](Sanguine Utilities-1.3.2.jar) 
    UCHI    SGCraft{1.11.2} [Greg's SG Craft](SGCraft-1.11.2-mc1.7.10.jar) 
    UCHI    SimpleLabels{@VERSION@} [SimpleLabels](SimpleLabels-1.7.10-1.0-9.jar) 
    UCHI    simplyjetpacks{1.5.3} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.5.3.jar) 
    UCHI    SolarFlux{1.7.10-0.8b} [Solar Flux](SolarFlux-1.7.10-0.8b.jar) 
    UCHI    soulcraft{1.3} [SoulCraft](soulcraft-v1.3-1.7.10.jar) 
    UCHI    StorageDrawers{1.7.10-1.10.0} [Storage Drawers](StorageDrawers-1.7.10-1.10.0.jar) 
    UCHI    Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCHI    Talismans 2{1.0.0} [Talismans 2](Talismans2-1.7.10-1.0.0.jar) 
    UCHI    TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
    UCHI    ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
    UCHI    theWeedMod{2.2.2a} [The Weed Mod](theweedmod-2.2.2a.jar) 
    UCHI    TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHI    Translocator{1.1.2.16} [Translocator](Translocator-1.7.10-1.1.2.16-universal.jar) 
    UCHI    vampirism{0.7.9} [Vampirism](Vampirism-1.7.10-0.7.9.jar) 
    UCHI    VeinMiner{0.21.2} [Vein Miner](VeinMiner-1.7.10_0.21.2.43.jar) 
    UCHI    VeinMinerModSupport{0.21.2} [Mod Support](VeinMiner-1.7.10_0.21.2.43.jar) 
    UCHI    WailaHarvestability{1.0.4} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.0.4.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
    UCHI    JCTweaks{1.25} [JCTweaks](jctweaks-1.7.10-1.25.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    UD  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.2B1-191.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4444' Renderer: 'Intel(R) HD Graphics 4400'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    CoFHCore: -[1.7.10]3.1.2-325
    AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
    ThermalFoundation: -[1.7.10]1.2.4-114
    Mantle Environment: Environment healthy.
    MineFactoryReloaded: -[1.7.10]2.8.2B1-191
    ThermalExpansion: -[1.7.10]4.1.2-240
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.2.0-171
    List of loaded APIs: 
        \* AppleCoreAPI (1.2.0) from AppleCore-mc1.7.10-1.3.2.jar
        \* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
        \* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
        \* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
        \* BloodUtils|API (1.0e) from BloodUtils-1.4_B0.jar
        \* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
        \* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
        \* CoFHAPI (1.7.10R1.0.3) from quantumenergy-1.7.10-0.6.jar
        \* CoFHAPI|block (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|core (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHAPI|energy (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHAPI|fluid (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|inventory (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|item (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|modhelpers (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|transport (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|world (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|gui|container (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|gui|element (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|slot (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|inventory (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|render (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|render|particle (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|util (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|util|helpers (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|world (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* CoFHLib|world|feature (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
        \* DraconicEvolution|API (1.2) from Draconic-Evolution-1.7.10-1.0.2h.jar
        \* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
        \* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
        \* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
        \* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
        \* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.462.jar
        \* GameAnalyticsAPI (1.0) from DimensionalPockets-1.7.10-0.11.4.1-universal.jar
        \* Guide-API|API (1.7.10-1.0.1-20) from Guide-API-1.7.10-1.0.1-20.jar
        \* IC2API (1.0) from SonarCore-1.7.10-1.1.3.jar
        \* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
        \* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.0.3.277.jar
        \* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0-122.jar
        \* OmnisCore|API (0.0.6) from OmnisCore-1.7.10 - 0.0.6-universal.jar
        \* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.5.1 (1).jar
        \* PracticalLogisticsAPI (1.4) from Practical-Logistics-1.7.10-0.2.4.jar
        \* ProjectEAPI (7) from ProjectE-1.7.10-PE1.10.0.jar
        \* Sanguimancy|API (@VERSION@) from Sanguimancy-1.7.10-1.1.9-35.jar
        \* SanguineExtras|API (1.1) from Sanguine Utilities-1.3.2.jar
        \* StarminerAPI (0.9.7) from Anti-Gravity-Mod-1.7.10.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.0.jar
        \* Thaumcraft|API (4.2.2.0) from tardismod-1.7.10-0.994-124-DS.jar
        \* WailaAPI (1.0) from WailaHarvestability-mc1.7.x-1.0.4.jar
        \* WormholeAPI (1.7.10R1.0.0) from DimensionalPockets-1.7.10-0.11.4.1-universal.jar
    DPAnalytics Crash Check: Will analyze crash-log before shutdown and send it to the Dimensional Pockets developer
    EnderIO: Found the following problem(s) with your installation:
                  \* The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from EnderTech-1.7.10-0.3.2.405.jar).
                    It is a supported version, but that difference may lead to problems.
                  \* An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8

**Comment by TehNut** [comment]
1. Report to NOVA
2. 1.7.10 is unsupported.
