### ISSUE TITLE
amerifrance.guideapi.page.PageText.setUnicodeFlag (Server crash)

### ISSUE THREAD

**Issue by Gamerbolts** [TeamAmeriFrance/Guide-API#37]
Hi I am getting a server crash I am pretty sure it is because of the Blood Magic update. I am using BM v2.0.3-52 and Guide API (i tried both v38 and v40) And I get a crash going from Initialized to Post Initialized. Here is my error log http://pastebin.com/BYcMqS8B.

Also I tried to remove Guide API completely and the server loaded up.

Any help is appreciated! Thank you

**Comment by TehNut** [comment]
@WayofTime: setUnicodeFlag is a client only method.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/087982eb9d8138ab8cfe3ec66b2fae0eab8764ba
