### ISSUE TITLE
Update to latest version of Forge causes crash.

### ISSUE THREAD

**Issue by lilrichy** [TeamAmeriFrance/Guide-API#38]
Updated to forge 12.18.1.2043 and This mod now crashes. Tested it with out any other mods installed just to be sure.

http://pastebin.com/ub8yBCyA

**Comment by TehNut** [comment]
Forge issue. Requested an overload be added to solve this. Do not report to them.

**Comment by TehNut** [comment]
Fixed as of Forge build 2045.
