### ISSUE TITLE
[Issue] Unexpected error with Sanguine scientiem

### ISSUE THREAD

**Issue by Moustik2002** [TeamAmeriFrance/Guide-API#39]
Hi,
when i open the book my client crashes and i get this crash report : http://pastebin.com/spj621Vd

**Comment by TehNut** [comment]
Please try with Forge build 2045.

**Comment by TehNut** [comment]
Closing due to no response in 2 weeks.

**Comment by Moustik2002** [comment]
Oh sorry about the delay, i've completly forget about this post, so tested in 2045 et 2065 with the same result.
