### ISSUE TITLE
Entries listed in category in opposite alphabetical order

### ISSUE THREAD

**Issue by Da-Technomancer** [TeamAmeriFrance/Guide-API#41]
Entries are listed in the ingame book in the opposite of alphabetical order of the resourcelocation. An example is 

basicEntry.put(new ResourceLocation(Main.MODID, "basic1"), new Entry(introPages, "Introduction"));
basicEntry.put(new ResourceLocation(Main.MODID, "basic2"), new Entry(introPages, "Ores"));

ores above introduction, which is the same as with this: 
basicEntry.put(new ResourceLocation(Main.MODID, "basic2"), new Entry(introPages, "Ores"));
basicEntry.put(new ResourceLocation(Main.MODID, "basic1"), new Entry(introPages, "Introduction"));

Switching the ResourceLocations around puts them in the opposite order in the guide. All of the different ResourceLocations i've tested with also follow this rule of inverse alphabetical order. This doesn't seem like intended (or even convenient) behaviour, considering I would normally have given the top entry the location of basic1, followed by basic2, and so on in my nomenclature. However, logically it should sort them in the order they are added to the category IMO.

**Comment by Da-Technomancer** [comment]
After more testing, I found a case where it isn't inverse alphabetical order. 
with:
basicEntry.put(new ResourceLocation(Main.MODID, "basic99"), new Entry(introPages, "Introduction"));
basicEntry.put(new ResourceLocation(Main.MODID, "basic98"), new Entry(introPages, "Ores"));
basicEntry.put(new ResourceLocation(Main.MODID, "basic97"), new Entry(introPages, "Basics of Energy"));
basicEntry.put(new ResourceLocation(Main.MODID, "basic96"), new Entry(introPages, "Basics of Heat"));

everything is in inverse alphabetical order except that "basic96" is directly above "basic97". At this point, I'm not quite sure what the ordering system is.

**Comment by TehNut** [comment]
#32
