### ISSUE TITLE
Recipes that create multiple items only show 1 item.

### ISSUE THREAD

**Issue by Da-Technomancer** [TeamAmeriFrance/Guide-API#42]
To be precise, when using a PageIRecipe with a ShapedOreRecipe, and the itemstack produced has a stacksize greater than 1 (in this case 8 items are produced), the recipe in the guide book only shows it as 1 item being produced. I have not tested with any other type of recipe.

**Comment by TehNut** [comment]
We currently don't call `RenderItem#renderItemOverlayIntoGUI(...)` in `GuiHelper.drawItemStack(...)`.
