### ISSUE TITLE
Some items not displayed properly in recipes

### ISSUE THREAD

**Issue by Da-Technomancer** [TeamAmeriFrance/Guide-API#43]
At this point I have found a few items that display a missing texture in the crafting pages of a guideAPI book. 

Stained glass when using "glass" oreDict
Wooden Slabs, when using "slabWood" oreDict

**Comment by TehNut** [comment]
This is caused by those giving a stack with `OreDictionary.WILDCARD_VALUE` as a meta which (for some reason) we don't handle right now.
