### ISSUE TITLE
Attempting to download the guide for 1.10.2 gets the 1.8 guide

### ISSUE THREAD

**Issue by MentalMouse** [TeamAmeriFrance/Guide-API#44]
The mod downloaded does not in fact load under 1.10.2.  I get apparently the same file if I try to download for 1.9.4.

**Comment by TehNut** [comment]
Unable to reproduce. Just downloaded [this file](https://minecraft.curseforge.com/projects/guide-api/files/2325317) from CurseForge and it launched perfectly fine. If you are using the old Curse site, stop.

**Comment by MentalMouse** [comment]
Poking at it again... aha!  The Bright Orange Download Button (tm) gets the 1.8 file.  To get the 1.10 file, I had to hit the faded gray download button below it....

**Comment by TehNut** [comment]
The orange button downloads the latest build marked as Release. You should _always_ download versions from the file list.
