### ISSUE TITLE
Need help with a crash (Silent's Gems)

### ISSUE THREAD

**Issue by SilentChaos512** [TeamAmeriFrance/Guide-API#45]
Using Guide-API to provide a guide book for Silent's Gems. Worked with no issues before Guide-API 2.0.1. Currently working with 2.0.2-45 and have fixed several crashes, but I'm having trouble figuring out this one.

Here's the [crash report](https://gist.github.com/SilentChaos512/77c5b674e1d6810a48cd8b200496be8e).
And here's the [offending line](https://github.com/SilentChaos512/SilentGems/blob/master/common/net/silentchaos512/gems/guide/GuideSilentGems.java#L358) in my project.

Any assistance you can provide would be greatly appreciated.

**Comment by TehNut** [comment]
https://github.com/SilentChaos512/SilentGems/blob/master/common/net/silentchaos512/gems/SilentGems.java#L50

`after:guideapi`

**Comment by SilentChaos512** [comment]
Well, I feel silly. Thank you.
