### ISSUE TITLE
Book Texture Glitch

### ISSUE THREAD

**Issue by WenXin20** [TeamAmeriFrance/Guide-API#49]
Forge 2092-1.10.2
I have three mods that use the guide-api, which are [Silent's Gems](http://minecraft.curseforge.com/projects/silents-gems), [Modular Routers](https://minecraft.curseforge.com/projects/modular-routers), & [JAPTA](https://minecraft.curseforge.com/projects/japta), and one of the books appear with a black and red book texture instead of the normal book texture by that mod. For example, Japta's book is usually grey and black, but sometimes it appears solid black with red pages.
![2016-09-27_14 12 14](https://cloud.githubusercontent.com/assets/12000593/18888120/9fcae34c-84bc-11e6-997d-1a27e992bb14.png) 
(In this pic, Silent's Gems guide book is glitched)

**Comment by TehNut** [comment]
Could I get a client log?

**Comment by WenXin20** [comment]
Log:
[fml-client-latest .txt](https://github.com/TeamAmeriFrance/Guide-API/files/496466/fml-client-latest.txt)

**Comment by TehNut** [comment]
This should be solved in the 1.11 builds.
