### ISSUE TITLE
Sample guide book does not compile using Forge 1.10.2

### ISSUE THREAD

**Issue by Lothrazar** [TeamAmeriFrance/Guide-API#51]
Log

http://pastebin.com/562DVQZ1

My properties & build.gradle are 

  deobfCompile "info.amerifrance.guideapi:Guide-API:${mc_version}-${guideapi_version}"
guideapi_version=2.0.2-45

i got the source code from this page http://guide-api.readthedocs.io/en/latest/createabook/basic/

actual code
https://github.com/PrinceOfAmber/Cyclic/commit/af91678ea79b15be464a2c0ae385f2d450e34b58

**Comment by TehNut** [comment]
#45 You are loading before GuideAPI can create it's registry.

**Comment by Lothrazar** [comment]
I see.  I had put the code in FMLPreInitializationEvent  , which is what the documentation says to do here http://guide-api.readthedocs.io/en/latest/createabook/basic/

Should i move it instead to FMLInitializationEvent  or FMLPostInitializationEvent  ?

EDIT: I know, i probably need a dependency order injection something like

dependencies = "after:JEI;after:Baubles", is that right?

**Comment by TehNut** [comment]
Well if you read the solution in the issue I referenced...
