### ISSUE TITLE
(Question) How to have a dynamic entry?

### ISSUE THREAD

**Issue by Da-Technomancer** [TeamAmeriFrance/Guide-API#54]
Sorry to bother you, but is it possible (and if so how?) to make an entry where the contents changes dynamically? By which I mean every time the entry is viewed (not just on entry creation) the contents (page list) can be changed. Specifically, I'm trying to make an entry which grows as the player discovers new things. I'm on 1.10 by the way.

**Comment by tterrag1098** [comment]
`PageText.draw` is public and nonfinal (which is arguably bad, but meh) so you should be able to change it on the fly.

**Comment by Da-Technomancer** [comment]
I already saw that, but what I was looking for was a way to change the **number** of pages, not just their content.

**Comment by TehNut** [comment]
Entries can be changed at any time. Just modify the Pages contained in them whenever you want to.

**Comment by Da-Technomancer** [comment]
Is there a method that's called every time a certain entry is viewed so I can change the pages then?

**Comment by TehNut** [comment]
https://github.com/TeamAmeriFrance/Guide-API/blob/1.10/src/main/java/amerifrance/guideapi/api/impl/abstraction/EntryAbstract.java#L68

If you create your own entry type, you can override that.

**Comment by Da-Technomancer** [comment]
Thanks, that should work.

**Comment by Tombenpotter** [comment]
Heh, I designed this in a couple of days but I did think of this possibility :P
