### ISSUE TITLE
NullPointerException on creating new Book instance

### ISSUE THREAD

**Issue by ThePuzzlemaker** [TeamAmeriFrance/Guide-API#57]
Whenever I do this line of code, my game crashes:
`Book book = new Book()`
[http://pastebin.com/X2Guwb0k](http://pastebin.com/X2Guwb0k)
PlanckGuide.java:
[http://pastebin.com/fRVyhvK3](http://pastebin.com/fRVyhvK3)

**Comment by TehNut** [comment]
You need to load after Guide-API

**Comment by ThePuzzlemaker** [comment]
Thanks!
