### ISSUE TITLE
ItemStack doesn't render when the item is set to Blocks.SKULL

### ISSUE THREAD

**Issue by The-Fireplace** [TeamAmeriFrance/Guide-API#61]
![image](https://cloud.githubusercontent.com/assets/5914284/23595804/656cea5a-01ea-11e7-9b79-5bd83cb383bd.png)
`categories.add(new CategoryItemStack(entries, proxy.translateToLocal("overlord.guide.1"), new ItemStack(Blocks.SKULL)));`

**Comment by TehNut** [comment]
You want `Items.SKULL`. It's one of the many Item -> Block mappings that aren't done properly.
