### ISSUE TITLE
[1.11-2.1.0-50] crashes dedicated server Forge 1.11.2 build 2253

### ISSUE THREAD

**Issue by kreezxil** [TeamAmeriFrance/Guide-API#62]
Notes:
     on startup -- Silent Lib did an update, reporting there too

crash report:
https://gist.github.com/24a9528cb92880f3bc824a83398df868

fml server latest:
https://gist.github.com/b4c1d873dcbb2a20427b17e1e3af03ab

**Comment by TehNut** [comment]
His items are being referenced before being initialized. He needs to load before GAPI.
