### ISSUE TITLE
Is there a way to add potion recipes to guide

### ISSUE THREAD

**Issue by Lothrazar** [TeamAmeriFrance/Guide-API#65]
Potions use IBrewingRecipe , which does not extend IRecipe.  So the crafting recipe page wont work

I looked through the documentation and source code, and it seems like we have PageIRecipe, PageFurnaceRecipe, and a few pages for sounds and text and images, but no text for potions.

**Comment by TehNut** [comment]
Just create a new page type. You're not limited to what we provide.

**Comment by Lothrazar** [comment]
Oh that makes sense. Thanks

**Comment by Lothrazar** [comment]
Would you consider accepting a pull request with a PageBrewingRecipe into the base GuideAPI mod? 

I havent made one yet.. but existing pages have nice clean readable code so ill probably be making one for my own use anyway.

Anyway let me know if you accept submissions like that @TehNut

**Comment by TehNut** [comment]
If it supports a vanilla system, I'll gladly take new default page types.

**Comment by Lothrazar** [comment]
Opinions of my texture // where to put output icon?  Got this so far  
![potion](https://cloud.githubusercontent.com/assets/621529/25551523/dd260f02-2c3a-11e7-90ae-2ba2e63e5d34.PNG)  

Havent cloned repo yet just working in my own codebase.  Ill try to get pr by sunday

**Comment by ChloeDawn** [comment]
I'd recommend a more compact layout, similar to JEI's.. something like this

![](http://i.imgur.com/qKIMxqt.png)

**Comment by ChloeDawn** [comment]
Hopefully once https://github.com/TeamAmeriFrance/Guide-API/issues/60 gets resolved, you'll be able to directly render the potion recipe from JEI when's its present, allowing your guide books to support modified recipes via CraftTweaker scripts etc

**Comment by TehNut** [comment]
Currently asking Kit to redo all the existing page stuff like what she posted

**Comment by ChloeDawn** [comment]
Re-texture PR incoming (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by Lothrazar** [comment]
Wow so pretty!  Cool ill wait until textures are in so i wont worry about that and stay in the code.

**Comment by Lothrazar** [comment]
forked and pulled code in from my own repository.  This is what i have so far.  Without textures and subject to change.  https://github.com/TeamAmeriFrance/Guide-API/pull/66

Let me know if anything needs to change with this.  I couldnt get it running with the standalone repo, so technically untested but i had started out just in my own repo where i had it working https://github.com/PrinceOfAmber/Cyclic/blob/249946a1669a0fded529357a141fbf2385c19b9d/src/main/java/com/lothrazar/cyclicmagic/PageBrewingRecipe.java

If you need anything and im not responding right away ping me on twitter, otherwise i will check back in periodically https://twitter.com/lothrazar
