### ISSUE TITLE
Exception in server tick loop  java.lang.ArrayIndexOutOfBoundsE

### ISSUE THREAD

**Issue by darkshadow1809** [TeamAmeriFrance/Guide-API#76]
[crash-2017-06-29_04.31.32-server.txt](https://github.com/TeamAmeriFrance/Guide-API/files/1110743/crash-2017-06-29_04.31.32-server.txt)

1.11.2 - V1.11-80

On server load crash. If you need more information please dont hesitate to let me know

**Comment by TehNut** [comment]
TerrainControl issue. Completely unrelated to GuideAPI.
