### ISSUE TITLE
[1.12] New Forge registry system issues

### ISSUE THREAD

**Issue by desht** [TeamAmeriFrance/Guide-API#77]
I note that ``Guidebook#buildBook()`` is currently called from Guide-API's preInit().  This doesn't quite work with the new Forge registry system; if I have a registry class in my mod using ``@ObjectHolder`` to inject my blocks and items, and using registry events to register those blocks/items, that doesn't happen until _after_ preInit().  So any block or item fields in my registry class are null at the point that ``Guidebook#buildBook()`` is called, which is a problem for using those blocks/items as category icons.

I suppose buildBook() needs to be called from init() rather than preInit()?

**Comment by Da-Technomancer** [comment]
This affects way more than just entry/category items, it's also a problem for any recipe involving a modded ingredient/product. This needs to be fixed ASAP.

**Comment by TehNut** [comment]
...I thought I fixed this. Maybe I just didn't push it?

**Comment by TehNut** [comment]
Aight. That commit should fix this.
