### ISSUE TITLE
Content too big/overflows screen

### ISSUE THREAD

**Issue by Parahacker** [TeamAmeriFrance/Guide-API#79]
Not sure what's causing this. Using "Universal Interdimensional Escape' mod pack default settings, screenshot of Sanguimancy manual (but all manuals using Guide-API are doing this):

![2017-07-25_05 57 50](https://user-images.githubusercontent.com/11980414/28566886-7fabf3b0-70fe-11e7-95db-af55cb47f124.png)

**Comment by TehNut** [comment]
1.7.10 is not supported.

**Comment by Jonius7** [comment]
As seen here:
https://www.reddit.com/r/feedthebeast/comments/1hbwulp/blood_magic_book_is_broken_somehow

Downgrade to `1.0.1-20`

I also have my own fork, but the Entries use large text and there are no tabs on the side. Can't tell what's different between the two fonts as they both use the default Minecraft FontRenderer. Might be enabling Unicode

**Comment by Parahacker** [comment]
Wow.

You just gave me hope that the internet is not, in fact, dead. Reviving an eight-year-old issue and addressing it meaningfully? Sir. This was a gift.

**Comment by Jonius7** [comment]
I am building my own 1.7.10 modpack (or rather rebuilding it from a few years ago) and have been fixing a few mods here and there.
