### ISSUE TITLE
[1.12] Allow using ResourceLocation as a constructor argument for PageIRecipe for json recipes

### ISSUE THREAD

**Issue by The-Fireplace** [TeamAmeriFrance/Guide-API#80]
As the title says, it would be nice to be able to construct a PageIRecipe from a ResourceLocation, so it can load directly from the recipe json files. It can be done anyways, using `new PageIRecipe(CraftingManager.getRecipe(ResourceLocation))`, so adding that constructor would allow people to skip a step.

**Comment by TehNut** [comment]
Oh I don't close things until they're in a release

**Comment by The-Fireplace** [comment]
Got it. Any estimate on how long it'll be?

EDIT: Lol,  wrong button. Didn't mean to close it again.

**Comment by TehNut** [comment]
I need to figure out a proper fix for #77 first. Almost there.
