### ISSUE TITLE
Allow priority specification for @GuideBook

### ISSUE THREAD

**Issue by The-Fireplace** [TeamAmeriFrance/Guide-API#81]
I have a mod and an addon for it that both use guide books with `@GuideBook`. I need the addon's guide book to load after the base mod's, and right now, that isn't happening. I see two ways to solve this. The first one, which would probably take a lot more work, is to figure out which mods add which books, and load them in the same order Forge loads the mods.
The second, and likely easier option, would me to make it so modders using `@GuideBook` can specify a priority in parenthesis, and if they don't, it is normal by default. Much like how `@SubscribeEvent` does things.

**Comment by The-Fireplace** [comment]
Hey @TehNut, is there any chance you can copy the changes made in that PR to the 1.11 branch?

**Comment by TehNut** [comment]
git pls
