### ISSUE TITLE
[1.10.2] Documentation?

### ISSUE THREAD

**Issue by Hazmatik** [TeamAmeriFrance/Guide-API#85]
I know this may be me just being n00b at modding but I can't seem to find any documentation on how to use this in 1.10.2. The docs I've looked at all have it using the @GuideBook annotation for the class to make a book and importing amerifrance.guideapi.api.GuideBook yet the 1.10.2 version I got from CurseForge doesn't seem to have the GuideBook class in it.

**Comment by The-Fireplace** [comment]
On 1.10.2, you have to manually check if Guide API is loaded and build and register your book if it is. You will need to do this through an interface if you don't want Guide API to be a hard dependency. See how I did it for Overlord.
https://github.com/The-Fireplace/Overlord/blob/1.10.2/src/main/java/the_fireplace/overlord/compat/guide/OverlordGuide.java
https://github.com/The-Fireplace/Overlord/blob/1.10.2/src/main/java/the_fireplace/overlord/Overlord.java#L192-L196
Also, in your mod's dependencies section, you will want to add `after:guideapi`.
