### ISSUE TITLE
[1.12] PageIRecipe.fromJson only seems to work on Vanilla recipes

### ISSUE THREAD

**Issue by The-Fireplace** [TeamAmeriFrance/Guide-API#90]
I will resolve this one. After my issues with null pages, trying to track down the cause, it turns out the method used in fromJson only works for Vanilla recipes. Every Forge method I have found so far does the same. I am self-assigning this. I caused this issue, and I will fix it.

**Comment by The-Fireplace** [comment]
Ok, after looking further into it, mod recipes are not loaded until after the book is built. Which means I will have to change when books are built to allow loading of PageIRecipes from json files.
EDIT: Cannot do that either. That would create and issue with book crafting recipes. Perhaps I can force-load mod recipes early.

**Comment by TehNut** [comment]
An alternative could be `PageJsonRecipe` which only stores the `ResourceLocation` and loads the `IRecipe` as needed. That would be a bit less performant though. Could loop through every book during `FMLLoadCompleteEvent` and find all the JSON recipe pages to construct the `IRecipe`'s. A slightly longer loading period, but shouldn't be horrible.

Perhaps something like the following:

```java
public class PageJsonRecipe extends PageIRecipe {

    private final ResourceLocation recipeId;

    public PageJsonRecipe(ResourceLocation recipeId) {
        super(null);
        
        this.recipeId = recipeId;
    }
    
    // Call from FMLLoadCompleteEvent
    public void init() {
        this.recipe = CraftingManager.getRecipe(recipeId);
        this.iRecipeRenderer = getRenderer(recipe);
    }
}
```

**Comment by The-Fireplace** [comment]
Interesting. That sounds like a better idea than mine. I'll give it a shot.

**Comment by tterrag1098** [comment]
Also to note is that all recipes have a ResourceLocation, not just JSON ones. So this should work for all recipes.
