### ISSUE TITLE
Crash (NPE) with recipes that use an enchanted book

### ISSUE THREAD

**Issue by Xilef11** [TeamAmeriFrance/Guide-API#97]
I'm using guide-api for my mod's documentation, but I get a NPE (that crashes the game) when opening the page for a recipe that uses an enchanted book because the CreativeTab passed to getSubItems() is null. (the recipe is defined in json with minecraft:enchanted_book and it works fine for crafting and in JEI)

[log + recipe json](https://gist.github.com/Xilef11/e64c8172dfc40400e99c3b349574212e)

I'm not sure if this is a bug or if I'm doing something wrong though...

**Comment by TehNut** [comment]
~~I am unable to reproduce this with the following json. All I did was take yours and replace it with vanilla alternatives.~~

I had made a change I thought I'd removed. Removed that and I can reproduce.

```json
{
  "result": {
    "item": "minecraft:potato"
  },
  "ingredients": [
    {
      "item": "minecraft:enchanted_book",
      "data": 32767
    },
    {
      "item": "minecraft:bone_block"
    }
  ],
  "type": "minecraft:crafting_shapeless"
}
```

**Comment by Xilef11** [comment]
Thanks! good to know it wasn't me doing something stupid :p
